language: node_js

node_js:
  - "8.12"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

scripts:
  - npm install
  - npm run build

deploy:
  keep-history: true
  local-dir: build
  target-branch: master
