language: node_js

node_js:
  - "8.12"

notifications:
  email: false

cache:
  directories:
    - "node_modules"

scripts:
  - npm install
  - git add -f --all build/
  - npm run build

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  skip-cleanup: true
  keep-history: true
  local-dir: build
  target-branch: gh-pages

  on:
    branch: master
